# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'VDownloader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VDownloader
  pod 'Disk' , '~> 0.3.0'
  pod 'SCLAlertView'
  pod 'SVProgressHUD'
  
end
